nacos:
  ip: 47.108.76.44
  grpcPort: 9848
  port: 8848
  clientConfig:
    timeoutMs: 5000
    listenInterval: 10000
    notLoadCacheAtStart: true
    logDir: data\nacos\log
  instanceConfig:
    weight: 1
    enable: true
    healthy: true
    ephemeral: true